### ISSUE TITLE
Issue with Grape: undefined local variable or method `settings' for #<Grape::Endpoint>

### ISSUE THREAD

**Issue by franklsf95** [jrhe/grape-active_model_serializers#35] opened 2014-12-29 09:00 UTC
I encountered the following error when using `grape-active_model_serializers 1.2.0` with `grape 0.10.1`. I tried version `1.3.1` and the issue still exists.

    undefined local variable or method `settings' for #<Grape::Endpoint:0x007f9ed79dd690>

	grape-active_model_serializers (1.2.0) lib/grape-active_model_serializers/endpoint_extension.rb:12:in `namespace_options'
	grape-active_model_serializers (1.2.0) lib/grape-active_model_serializers/formatter.rb:27:in `build_options_from_endpoint'
	grape-active_model_serializers (1.2.0) lib/grape-active_model_serializers/formatter.rb:17:in `fetch_serializer'
	grape-active_model_serializers (1.2.0) lib/grape-active_model_serializers/formatter.rb:6:in `call'
	grape (0.10.1) lib/grape/middleware/formatter.rb:33:in `block in after'
	grape (0.10.1) lib/grape/middleware/formatter.rb:32:in `collect'
	grape (0.10.1) lib/grape/middleware/formatter.rb:32:in `after'
	grape (0.10.1) lib/grape/middleware/base.rb:25:in `call!'
	grape (0.10.1) lib/grape/middleware/base.rb:18:in `call'
	grape (0.10.1) lib/grape/middleware/base.rb:24:in `call!'
	grape (0.10.1) lib/grape/middleware/base.rb:18:in `call'
	grape (0.10.1) lib/grape/middleware/error.rb:27:in `block in call!'
	grape (0.10.1) lib/grape/middleware/error.rb:26:in `catch'
	grape (0.10.1) lib/grape/middleware/error.rb:26:in `call!'
	grape (0.10.1) lib/grape/middleware/base.rb:18:in `call'
	rack (1.5.2) lib/rack/head.rb:11:in `call'
	rack (1.5.2) lib/rack/builder.rb:138:in `call'
	grape (0.10.1) lib/grape/endpoint.rb:196:in `call!'
	grape (0.10.1) lib/grape/endpoint.rb:184:in `call'
	rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in `block in call'
	rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in `block in recognize'
	rack-mount (0.8.3) lib/rack/mount/code_generation.rb:75:in `optimized_each'
	rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in `recognize'
	rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in `call'
	grape (0.10.1) lib/grape/api.rb:102:in `call'
	grape (0.10.1) lib/grape/api.rb:33:in `call!'
	grape (0.10.1) lib/grape/api.rb:29:in `call'
	actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
	actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
	actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
	actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
	warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
	warden (1.2.3) lib/warden/manager.rb:34:in `catch'
	warden (1.2.3) lib/warden/manager.rb:34:in `call'
	rack (1.5.2) lib/rack/etag.rb:23:in `call'
	rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
	rack (1.5.2) lib/rack/head.rb:11:in `call'
	actionpack (4.1.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
	actionpack (4.1.8) lib/action_dispatch/middleware/flash.rb:254:in `call'
	rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
	rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
	actionpack (4.1.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
	activerecord (4.1.8) lib/active_record/query_cache.rb:36:in `call'
	activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
	activerecord (4.1.8) lib/active_record/migration.rb:380:in `call'
	actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
	activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
	actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
	actionpack (4.1.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
	actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
	actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
	actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
	railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
	activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
	activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
	activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
	railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
	rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
	activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
	rack (1.5.2) lib/rack/lock.rb:17:in `call'
	actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
	railties (4.1.8) lib/rails/engine.rb:514:in `call'
	railties (4.1.8) lib/rails/application.rb:144:in `call'
	newrelic_rpm (3.9.8.273) lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
	newrelic_rpm (3.9.8.273) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
	rack (1.5.2) lib/rack/lock.rb:17:in `call'
	rack (1.5.2) lib/rack/content_length.rb:14:in `call'
	rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'

**Comment by decademoon** [comment] 2015-01-03 00:20
I'm also getting this error. This commit may be the culprit [https://github.com/intridea/grape/commit/f8596829325123b5793d8f84b72e0b85ddffc207](https://github.com/intridea/grape/commit/f8596829325123b5793d8f84b72e0b85ddffc207).

**Comment by sethherr** [comment] 2015-01-03 23:09
Also encountered this. Reverted grape to 0.9.0 for now.

**Comment by JanStevens** [comment] 2015-01-05 12:30
I have the same issues, probably since Grape internally changed their settings classes. It also seems that after trying to resolve the settings issue I ran into something else:

https://github.com/playpasshq/grape-active_model_serializers/blob/master/lib%2Fgrape-active_model_serializers%2Fformatter.rb#L70

Here the endpoint settings are retrieved looking for a space method (or key) I tried looking for it but I dont really know the Grape stack.

**Comment by hcatlin** [comment] 2015-01-07 00:42
Same issue. 'Doh.

**Comment by siong1987** [comment] 2015-01-07 07:16
can someone set up a sample project to reproduce this issue so that i can jump in and figure out how to fix this?

**Comment by decademoon** [comment] 2015-01-07 08:13
Here's a simple `config.ru` file that demonstrates this error:

```ruby
#\ -p 3000
gem 'grape', '~> 0.10'
gem 'grape-active_model_serializers', '~> 1.3'

require 'active_model'
require 'grape'
require 'grape-active_model_serializers'

class User
  include ActiveModel::Model

  attr_accessor :name
end

class API < Grape::API
  format :json
  formatter :json, Grape::Formatter::ActiveModelSerializers

  get do
    User.new name: 'Bob'
  end
end

run API
```

Run with `rackup` and point your browser to `localhost:3000` and the error page will be displayed.

**Comment by lionelrudaz** [comment] 2015-01-08 20:54
Same issue here.

My repo is here: https://github.com/lionelrudaz/wellnow-api

I don't know if it helps.

**Comment by syntaxTerr0r** [comment] 2015-01-12 13:21
I reproduce this too.

**Comment by dblock** [comment] 2015-01-13 15:10
Fixed in https://github.com/jrhe/grape-active_model_serializers/pull/36.

**Closed** 2015-01-13 23:35 UTC

**Comment by squarism** [comment] 2015-01-27 00:22
Is this going to get released or tagged as a gem version?

**Comment by siong1987** [comment] 2015-01-27 02:38
@jrhe do you want to release a new version of the gem?

**Comment by sethherr** [comment] 2015-02-22 19:08
+1 to releasing a new version of the gem.

**Comment by hcatlin** [comment] 2015-02-22 19:22
+1

**Comment by siong1987** [comment] 2015-02-23 18:41
i will do it tonight :)

**Comment by akappen** [comment] 2015-02-25 22:22
Did this ever get released? The version available in rubygems is the buggy 1.3.1 still.

**Comment by crhan** [comment] 2015-02-26 06:22
+1

**Comment by themire** [comment] 2015-02-26 16:57
+1

**Comment by michaeldawson** [comment] 2015-02-27 04:10
+ 1

**Comment by BradleyJennings** [comment] 2015-02-27 10:02
+ 1

**Comment by ngdelcastillo** [comment] 2015-02-27 15:29
+1

**Comment by johnhamelink** [comment] 2015-02-27 21:43
Please release this :smile:

**Comment by fzf** [comment] 2015-02-27 21:54
+1 on sending to rubygems

**Comment by akappen** [comment] 2015-02-27 22:00
The current version on master works great in the meantime. I used a git source in my Gemfile:

gem "grape-active_model_serializers", git: "https://github.com/jrhe/grape-active_model_serializers.git"

Everything is happy using commit ca9c8f.

**Comment by jrhe** [comment] 2015-02-27 22:07
Oops. Didn't realise @siong1987 hadn't got around to this. Just bumped the version and pushed.

**Comment by siong1987** [comment] 2015-02-27 22:19
@jrhe my bad.  has been pretty busy lately :)  thanks!

**Comment by johnhamelink** [comment] 2015-02-28 11:18
Thanks very much @jrhe and @siong1987 :+1:
